In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

import lightgbm as lgb
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.model_selection import GridSearchCV, cross_validate

In [2]:
X = pd.read_csv('twitter_vec_dense.csv')
y = pd.read_csv('train_label.csv')

### Twitter dense vectors modeling

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=694)
forest = RandomForestClassifier(random_state=695)   

cv_results = cross_validate(forest, X_train, y_train, cv=5)
cv_results['test_score']

array([0.69085074, 0.69154057, 0.69155557, 0.68971102, 0.68853664])

In [4]:
clf = RandomForestClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6946277323223841

In [5]:
adaboost = AdaBoostClassifier(random_state=695)   

cv_results = cross_validate(adaboost, X_train, y_train, cv=5)
cv_results['test_score']

array([0.63737384, 0.63780874, 0.63830362, 0.63765877, 0.63688852])

In [6]:
clf = AdaBoostClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6347145907814862

In [7]:
g_boost = GradientBoostingClassifier(random_state=695)   

cv_results = cross_validate(g_boost, X_train, y_train, cv=5)
cv_results['test_score']

array([0.66024324, 0.66136796, 0.66247769, 0.66043819, 0.66118293])

In [8]:
clf = GradientBoostingClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6559493245675072

### Wiki dense vectors modeling

In [9]:
X1 = pd.read_csv('wiki_dense.csv')
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.2, random_state=694)

In [10]:
forest = RandomForestClassifier(random_state=695)   

cv_results = cross_validate(forest, X_train, y_train, cv=5)
cv_results['test_score']

array([0.66982589, 0.67296012, 0.67080065, 0.6718504 , 0.66904112])

In [11]:
clf = RandomForestClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6726251889531396

In [12]:
adaboost = AdaBoostClassifier(random_state=695)   

cv_results = cross_validate(adaboost, X_train, y_train, cv=5)
cv_results['test_score']

array([0.62209259, 0.62504686, 0.62452199, 0.62429705, 0.62102216])

In [13]:
clf = AdaBoostClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6209779974566307

In [14]:
g_boost = GradientBoostingClassifier(random_state=695)   

cv_results = cross_validate(g_boost, X_train, y_train, cv=5)
cv_results['test_score']

array([0.64262590, 0.64504612, 0.64652006, 0.644797045, 0.64102216])


In [15]:
clf = GradientBoostingClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6460397821340308