In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV, cross_validate

X = pd.read_csv('textstat_value.csv')
y = pd.read_csv('train_label.csv')

In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=694)
forest = RandomForestClassifier(random_state=695)   

cv_results = cross_validate(forest, X_train, y_train, cv=5)
cv_results['test_score']

array([0.69393998, 0.69485476, 0.69609946, 0.69980355, 0.69432531])

In [3]:
clf = RandomForestClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.7026297478225401

In [4]:
adaboost = AdaBoostClassifier(random_state=695)   

cv_results = cross_validate(adaboost, X_train, y_train, cv=5)
cv_results['test_score']

array([0.65949342, 0.66351244, 0.66214777, 0.66376738, 0.66179779])

In [5]:
clf = AdaBoostClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6611560333037406

In [6]:
g_boost = GradientBoostingClassifier(random_state=695)   

cv_results = cross_validate(g_boost, X_train, y_train, cv=5)
cv_results['test_score']

array([0.66430724, 0.66745647, 0.66838625, 0.66846123, 0.6665367 ])

In [7]:
clf = GradientBoostingClassifier(random_state=695)   
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6636274203997409

In [8]:
model = lgb.LGBMClassifier(learning_rate=0.1,max_depth=-1,random_state=694)

model.fit(X_train,y_train,eval_set=[(X_test,y_test),(X_train,y_train)],verbose = 20)
model.score(X_train,y_train), model.score(X_test,y_test)

[20]	training's binary_logloss: 0.606554	valid_0's binary_logloss: 0.608823
[40]	training's binary_logloss: 0.598785	valid_0's binary_logloss: 0.602343
[60]	training's binary_logloss: 0.595673	valid_0's binary_logloss: 0.600302
[80]	training's binary_logloss: 0.593566	valid_0's binary_logloss: 0.599218
[100]	training's binary_logloss: 0.591714	valid_0's binary_logloss: 0.598373


(0.6766512503974038, 0.6693739952491782)